import React, { Children } from "react"
import { Metadata } from "next";
import CounterP from "./CounterP/page";
import ServerComp from "./serverComp/page";
import { Contactus } from "./contactus/page";

export const metadata: Metadata = {
    title: "About Page",
    description: "Generated by create next app",
  };

function  about(  ){
    return(
        <>
        <Contactus/>
        <CounterP>
            <ServerComp/>
        </CounterP>
        <div>about page
          
          </div>
        
        </>

    )
}
export default about;