import React from "react";
import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "tamrin page",
    description: "Generated by create next app",
  };
function  Tamrin(
    {
        children,
      }: Readonly<{
        children: React.ReactNode;
      }>
){
    return(
        <>
        tamrins
                <div>layout Tamrin page</div>
                {children}
        </>

    )
}
export default Tamrin;